name: CD Pipeline - Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Amazon EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Logging into Docker Hub..."
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            echo "Stopping and removing old container..."
            docker stop demo-app || true
            docker rm demo-app || true

            echo "Pulling latest Docker image..."
            docker pull amarpal/demo-spring:latest

            echo "Running new container..."
            docker run -d --name demo-app -p 8080:8080 amarpal/demo-spring:latest
          EOF
