name: CI/CD for Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Set Version Tag
        run: |
          VERSION="v${{ github.run_number }}"  # Auto-incremented version
          echo "DOCKER_TAG=$VERSION" >> $GITHUB_ENV  # Version tag

      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: amarpal/demo-spring
          tags: latest,${{ env.DOCKER_TAG }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
